HaltonSingle<-function(n,b){
        n0<-n
        hn<-0
        f<-1/b
        while(n0>0){
                n1<-floor(n0/b)
                r<-n0-n1*b
                hn<-hn+f*r
                f<-f/b
                n0<-n1
        }
        hn
}
HaltonSingle(5,2)
haltontotal<-function(n,b){
        hs<-rep(0,n)
        for(i in 1:n){
                hs[i]<-HaltonSingle(i,b)
        }
        hs
}
haltontotal(5,2)        
